services:
  postgresql:
    container_name: 'postgresql'
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=ecommerce'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'