services:
  postgresql:
    container_name: 'postgresql_test'
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=ecommerce_test'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5433:5432'